version: "3"

services:

  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=WMxP7Xd9MVZtvZ1D

  smtp:
    image: namshi/smtp:latest
    restart: always

  app:
    build: .
    image: phptourney
    restart: always
    volumes:
      - data:/var/www/html/data
      - ./app:/var/www/html
    environment:
      - PHPTOURNEY_DB_HOST=db
      - PHPTOURNEY_DB_PORT=3306
      - PHPTOURNEY_DB_ROOT_PASSWORD=WMxP7Xd9MVZtvZ1D
      - PHPTOURNEY_DB_USERNAME=phptourney
      - PHPTOURNEY_DB_PASSWORD=wKKdiJjILUyJ6XmV
      - PHPTOURNEY_DB_DATABASE=phptourney
      - PHPTOURNEY_MAIL_FROM_ADDRESS=
      - PHPTOURNEY_TOURNEY_NAME=phpTourney
      - PHPTOURNEY_HOST=http://
      - PHPTOURNEY_PATH=/
      - PHPTOURNEY_CONVERT=convert
      - PHPTOURNEY_RECAPTCHA_KEY=
      - PHPTOURNEY_RECAPTCHA_SECRET=
      - PHPTOURNEY_DEBUG=1
    ports:
      - 8080:80
    depends_on:
      - db
      - smtp
    links:
      - smtp:mail

volumes:
  db:
  data:
